local_backend: true

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

site_url: https://aitken.netlify.app/
logo_url: https://aitken.netlify.app/img/AitkenAudio-round-logo-8.png

media_folder: "static/img" # Media files will be stored in the repo under images/uploads
public_folder: "/img/"

collections:
        
- name: 'pages'
  label: 'Pages'
  files:
    - file: 'content/_index.md'
      label: 'Home'
      name: 'home'
      fields:
        - { label: 'Title', name: 'title', widget: 'string'}
        - { label: 'Body', name: 'body', widget: 'markdown'}
    - file: 'content/about-me.md'
      label: 'About Me'
      name: 'about-me'
      fields:
        - { label: 'Title', name: 'title', widget: 'string'}
        - { label: 'Body', name: 'body', widget: 'markdown'}
    - file: 'content/services.md'
      label: 'Services'
      name: 'services'
      fields:
        - { label: 'Title', name: 'title', widget: 'string'}
        - { label: 'Body', name: 'body', widget: 'markdown'}
    - file: 'content/pedals-for-sale.md'
      label: 'Pedals for Sale Page'
      name: 'pedals-for-sale'
      fields:
        - { label: 'Title', name: 'title', widget: 'string'}
        - { label: 'Body', name: 'body', widget: 'markdown'}
    - file: 'content/blog-feed.md'
      label: 'Blog Links'
      name: 'blog-links'
      fields:
        - { label: 'Title', name: 'title', widget: 'string'}
        - { label: 'Body', name: 'body', widget: 'markdown'}
    - file: 'content/contact.md'
      label: 'Contact'
      name: 'contact'
      fields:
        - { label: 'Title', name: 'title', widget: 'string'}
        - { label: 'Body', name: 'body', widget: 'markdown'}
    - file: 'data/footer.yaml'
      label: 'Footer'
      name: 'footer'
      fields:
        - label: 'Address'
          name: 'address'
          widget: 'object'
          fields:
          - {label: 'Name', name: 'name', widget: 'string'}
          - {label: 'house', name: 'house', widget: 'string'}
          - {label: 'street', name: 'street', widget: 'string'}
          - {label: 'Town or city', name: 'town', widget: 'string'}
          - {label: 'Postcode', name: 'postcode', widget: 'string'}
          - {label: 'County', name: 'county', widget: 'string'}
        - label: 'Contact information'
          name: 'contact_info'
          widget: 'object'
          fields:
            - {label: 'Phone number', name: 'tel', hint: 'Use only numbers or spaces'}
            - {label: 'E-mail', name: 'email'}
        - label: 'Social Media'
          name: 'socials'
          widget: 'list'
          allow_add: false
          fields:
            - {label: 'Name', name: 'name', widget: 'string'}
            - {label: 'Web address', name: 'url', widget: 'string'}
            - {label: 'Hover text', name: 'hover', widget: 'string'}
            
            
          